(declare-const dog Int)
(declare-const cat Int)
(declare-const mouse Int)
(assert (>= dog 1))
(assert (>= cat 1))
(assert (>= mouse 1))
(assert (= (+ (+ dog cat) mouse) 100))
(assert (= (+(+ (* 100 dog) (* 1500 cat))(* 25 mouse)) 10000))
(check-sat)
(get-value (cat dog mouse))
